export const PLAY_FEATURED_VIDEO = 'PLAY_FEATURED_VIDEO';
export const OPEN_THEME_DETAILS = 'OPEN_THEME_DETAILS';
export const SAVE_THEMES = 'SAVE_THEMES';
export const CLOSE_THEME_DETAILS = 'CLOSE_THEME_DETAILS';
